name: build graalvm

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - 21-JDK/**

jobs:
  pterodactyl-graalvm:
    name: "pterodactyl-graalvm:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 11
          - 17
          - 19
          - 17-JDK
          - 20-JDK
          - 21-JDK
          - 22-JDK
          - 23-JDK
          - 24-JDK
          - 11-EE
          - 17-EE
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/gg-green/yolks:graal_${{ matrix.tag }}

